// 100 correos variados y breves para las categorías
window.EMAILS = [
  // PETICIONES (25)
  {title:"Vacaciones",body:"¿Podés avisarme si quedan días disponibles para usar?",category:"peticiones"},
  {title:"Turno médico",body:"¿Me ayudás a pedir una consulta para mañana?",category:"peticiones"},
  {title:"Archivo requerido",body:"¿Podrías enviarme el PDF del informe trimestral?",category:"peticiones"},
  {title:"Reunión",body:"¿Te animás a sumarte a la reunión de las 15?",category:"peticiones"},
  {title:"Cambio de horario",body:"¿Es posible adelantar la cita al martes?",category:"peticiones"},
  {title:"Soporte",body:"¿Pueden ayudarme con la configuración del correo?",category:"peticiones"},
  {title:"Capacitación",body:"¿Me inscribís en el curso de Excel avanzado?",category:"peticiones"},
  {title:"Acceso",body:"¿Podrías darme permisos para ver la carpeta de ventas?",category:"peticiones"},
  {title:"Solicitud de materiales",body:"¿Me pueden enviar más hojas para impresión?",category:"peticiones"},
  {title:"Contacto proveedor",body:"¿Podrían compartir el teléfono del nuevo proveedor?",category:"peticiones"},
  {title:"Viaje",body:"¿Me autorizan el viaje a Córdoba la próxima semana?",category:"peticiones"},
  {title:"Horario de salida",body:"¿Me dejan salir antes el viernes por un trámite?",category:"peticiones"},
  {title:"Cambio de clave",body:"¿Me ayudan a restablecer mi contraseña?",category:"peticiones"},
  {title:"Ingreso temprano",body:"¿Puedo entrar antes el lunes para organizar el evento?",category:"peticiones"},
  {title:"Reserva",body:"¿Podrías reservar la sala 2 para las 11h?",category:"peticiones"},
  {title:"Formato",body:"¿Me indicás cómo llenar el formulario de gastos?",category:"peticiones"},
  {title:"Impresión",body:"¿Pueden imprimir 10 copias del contrato?",category:"peticiones"},
  {title:"Beneficios",body:"¿Me cuentan si tengo acceso a comedor?",category:"peticiones"},
  {title:"Notificación",body:"¿Avisan cuando llegue el paquete que pedí?",category:"peticiones"},
  {title:"Cambio de monitor",body:"¿Puedo cambiar mi monitor por uno más grande?",category:"peticiones"},
  {title:"Extensión",body:"¿Se puede extender el plazo de entrega?",category:"peticiones"},
  {title:"Actualización",body:"¿Podrían actualizar mi dirección en el sistema?",category:"peticiones"},
  {title:"Permiso especial",body:"¿Puedo faltar el martes por asuntos personales?",category:"peticiones"},
  {title:"Manual",body:"¿Tienen el manual del equipo para enviarme?",category:"peticiones"},
  {title:"Recibo",body:"¿Me reenvían el recibo del último pago?",category:"peticiones"},
  // QUEJAS (25)
  {title:"Temperatura",body:"Hace demasiado calor en la oficina, cuesta concentrarse.",category:"quejas"},
  {title:"Ruido",body:"El volumen de la música en el pasillo es molesto.",category:"quejas"},
  {title:"Limpieza",body:"Encontré el baño sucio dos veces esta semana.",category:"quejas"},
  {title:"Computadora lenta",body:"La PC tarda mucho en iniciar hoy.",category:"quejas"},
  {title:"Demora",body:"Todavía no contestan mi solicitud enviada hace días.",category:"quejas"},
  {title:"Espacio reducido",body:"La sala de reuniones está siempre ocupada.",category:"quejas"},
  {title:"Café",body:"La máquina de café no funciona desde la mañana.",category:"quejas"},
  {title:"Sillas",body:"Varias sillas del comedor están rotas.",category:"quejas"},
  {title:"Internet",body:"La conexión se cae seguido en mi sector.",category:"quejas"},
  {title:"Estacionamiento",body:"No encontré lugar para estacionar hoy.",category:"quejas"},
  {title:"Ruidos",body:"El aire acondicionado hace un zumbido molesto.",category:"quejas"},
  {title:"Luz",body:"Una lámpara del sector B parpadea todo el tiempo.",category:"quejas"},
  {title:"Demora en atención",body:"Tardaron mucho en responder mi consulta.",category:"quejas"},
  {title:"Ambiente",body:"El ambiente del comedor es muy ruidoso al mediodía.",category:"quejas"},
  {title:"Correo no entregado",body:"No recibí el paquete que esperaba.",category:"quejas"},
  {title:"Demasiada espera",body:"Tuve que esperar mucho en recepción.",category:"quejas"},
  {title:"Horario",body:"El horario de la cafetería no es conveniente.",category:"quejas"},
  {title:"Falta de insumos",body:"No hay hojas en la impresora desde ayer.",category:"quejas"},
  {title:"Poca variedad",body:"El menú del comedor es muy repetitivo.",category:"quejas"},
  {title:"Mal olor",body:"Hoy había mal olor en el pasillo principal.",category:"quejas"},
  {title:"Ruido exterior",body:"Las obras en la calle no dejan trabajar.",category:"quejas"},
  {title:"Espacio sucio",body:"Encontré basura en mi escritorio.",category:"quejas"},
  {title:"Demasiada gente",body:"La sala de espera estaba llena y fue incómodo.",category:"quejas"},
  {title:"Demora en facturación",body:"Tardaron mucho en facturar mi compra.",category:"quejas"},
  {title:"Temperatura baja",body:"El aire acondicionado está muy frío.",category:"quejas"},
  // RECLAMOS (25)
  {title:"Pago pendiente",body:"No recibí el pago acordado en la fecha estipulada.",category:"reclamos"},
  {title:"Producto defectuoso",body:"El mouse nuevo no funciona bien desde el inicio.",category:"reclamos"},
  {title:"Error en factura",body:"Me llegó una factura con montos que no corresponden.",category:"reclamos"},
  {title:"Entrega incompleta",body:"El pedido vino sin todos los insumos solicitados.",category:"reclamos"},
  {title:"Garantía",body:"Solicito la garantía del equipo recibido hace un mes.",category:"reclamos"},
  {title:"Devolución",body:"Pedí la devolución pero no tuve respuesta.",category:"reclamos"},
  {title:"Servicio técnico",body:"Hace días reclamé y no vinieron a reparar el equipo.",category:"reclamos"},
  {title:"Error en pedido",body:"El pedido que llegó no coincide con lo solicitado.",category:"reclamos"},
  {title:"Fallo en sistema",body:"El sistema de turnos no me permite ingresar.",category:"reclamos"},
  {title:"Acceso bloqueado",body:"No puedo entrar a la plataforma desde ayer.",category:"reclamos"},
  {title:"Envío demorado",body:"El envío superó el plazo prometido.",category:"reclamos"},
  {title:"Promoción no aplicada",body:"No se aplicó el descuento ofrecido.",category:"reclamos"},
  {title:"Atención deficiente",body:"La atención telefónica fue poco cordial.",category:"reclamos"},
  {title:"Cobro indebido",body:"Me cobraron de más en la última boleta.",category:"reclamos"},
  {title:"Producto dañado",body:"Recibí el paquete con el contenido roto.",category:"reclamos"},
  {title:"Fallo recurrente",body:"La impresora vuelve a fallar después del arreglo.",category:"reclamos"},
  {title:"Reembolso",body:"No llegó el reembolso del gasto aprobado.",category:"reclamos"},
  {title:"Plazo incumplido",body:"No cumplieron con la fecha prometida.",category:"reclamos"},
  {title:"Acceso restringido",body:"No tengo acceso a los informes que necesito.",category:"reclamos"},
  {title:"Error en envío",body:"Me entregaron un pedido equivocado.",category:"reclamos"},
  {title:"Defecto de fábrica",body:"El monitor tiene una mancha en la pantalla.",category:"reclamos"},
  {title:"Fallo en aplicación",body:"La app se cierra sola al iniciar.",category:"reclamos"},
  {title:"Demora en solución",body:"Todavía no resolvieron el problema que reporté.",category:"reclamos"},
  {title:"Mal funcionamiento",body:"El lector de tarjetas no reconoce ninguna.",category:"reclamos"},
  {title:"Cobranza errónea",body:"Figuro como deudor pero ya pagué.",category:"reclamos"},
  // SUGERENCIAS (25)
  {title:"Nuevo menú",body:"Podrían incorporar opciones sin gluten en el comedor.",category:"sugerencias"},
  {title:"Capacitaciones",body:"Sería bueno ofrecer charlas sobre liderazgo.",category:"sugerencias"},
  {title:"Horarios flexibles",body:"Quizás ayudaría probar horarios de entrada escalonados.",category:"sugerencias"},
  {title:"Comunicación",body:"Sugiero poner pizarras para anuncios en cada piso.",category:"sugerencias"},
  {title:"Plantas",body:"¿Y si ponemos más plantas en las oficinas para ambientar?",category:"sugerencias"},
  {title:"Agenda reuniones",body:"Sería útil recibir la agenda con anticipación.",category:"sugerencias"},
  {title:"Estacionamiento",body:"Podrían habilitar más lugares para bicicletas.",category:"sugerencias"},
  {title:"Reconocimientos",body:"Estaría bueno destacar los logros del equipo mensualmente.",category:"sugerencias"},
  {title:"App interna",body:"Una app interna ayudaría a centralizar la información.",category:"sugerencias"},
  {title:"Mejoras cafetería",body:"Podrían ofrecer más variedad de infusiones.",category:"sugerencias"},
  {title:"Flexibilidad",body:"Quizás permitir home office algunos días.",category:"sugerencias"},
  {title:"Salud",body:"Sería positivo tener pausas activas guiadas.",category:"sugerencias"},
  {title:"Buzón anónimo",body:"Un buzón anónimo para sugerencias podría sumar.",category:"sugerencias"},
  {title:"Música",body:"¿Probar música ambiente suave en áreas comunes?",category:"sugerencias"},
  {title:"Notificaciones",body:"Sería práctico recibir avisos por WhatsApp.",category:"sugerencias"},
  {title:"Eventos",body:"Podría organizarse un evento de integración trimestral.",category:"sugerencias"},
  {title:"Ahorro de papel",body:"Digitalizar más procesos ayudaría al medio ambiente.",category:"sugerencias"},
  {title:"Encuestas",body:"Encuestas mensuales mejorarían la comunicación.",category:"sugerencias"},
  {title:"Biblioteca",body:"Crear una pequeña biblioteca para empleados.",category:"sugerencias"},
  {title:"Menú digital",body:"Publicar el menú del día en la intranet.",category:"sugerencias"},
  {title:"Ergonomía",body:"Ofrecer charlas sobre ergonomía en el trabajo.",category:"sugerencias"},
  {title:"Bicicletero",body:"Agregar un bicicletero techado.",category:"sugerencias"},
  {title:"Café saludable",body:"Ofrecer opciones de café descafeinado.",category:"sugerencias"},
  {title:"Reconocimiento",body:"Sugerir reconocimientos espontáneos entre compañeros.",category:"sugerencias"},
  {title:"Red interna",body:"Una red social interna para compartir novedades.",category:"sugerencias"},
];